version: '3.8'

services:
  db:
    image: postgres:16
    container_name: candidates_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: candidates
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d candidates"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build: ./server
    container_name: candidates_server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/candidates?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: candidates_client
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_BASE_URL: "http://localhost:3000"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  db_data: